all : mutex.c
#	gcc -o serverConFork serverConForkEselect.c function.c
# Attenzione, non compilo il file che contiene il server con Fork e select!
	gcc -o mutex mutex.c -lpthread
	
mutex : mutex.c
#	gcc -o serverConFork serverConForkEselect.c function.c
# Attenzione, non compilo il file che contiene il server con Fork e select!
	gcc -o mutex mutex.c -lpthread